# For students: don't modify this file for the exercise
# To go on on Github Actions, look at the official doc.

name: Run tests on student program using expect

on:
  pull_request:
    branches:
      - "main"

jobs:
  test-expect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Install expect
        run: |
          sudo apt install expect

      # Workflow fail if exit code is different from 0
      - name: Test some operations
        run: |
          ./test.sh
